version: '3'

services:
  web:
    env_file: .env   # Change env_sample.txt to env.txt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"

# For db config read README.md/## Postgresql