version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./sock/:/sock/
      - ./:/code
      - ./logs/:/logs/
    entrypoint: sh entrypoint.sh
    env_file:
      - env.txt
    depends_on:
      - db
    networks:
      - django_nw
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "300M"

  db:
    image: mdillon/postgis:11-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    # ports:
    #   - 5432:5432
    env_file:
      - pg_env.txt
    networks:
      - django_nw
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "200M"

  redis:
    image: redis:alpine
    restart: always
    entrypoint: redis-server --appendonly yes
    # ports:
    #   - 6379:6379
    volumes:
      - ./_redis_data:/var/lib/redis
      - ./redis/rc.local:/etc/rc.local
    networks:
      - django_nw
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "200M"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: worker
    entrypoint: "celery -A project worker -f /logs/worker.log -l DEBUG"
    depends_on:
      - web
      - redis
    volumes:
      - ./logs/:/logs/
    env_file:
      - env.txt
    networks:
      - django_nw
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "250M"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf   # Change nginx/nginx-proxy-sample.conf to nginx-proxy.conf
      - ./frontend_app/dist:/var/www/frontend
      - ./sock/:/sock/
      - ./logs/nginx:/var/log/nginx
      - ./static:/static
    depends_on:
      - web
      - worker
    networks:
      - django_nw
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "200M"

networks:
  django_nw:
    driver: bridge
