version: '3.4'

services:
  db:
    image: mdillon/postgis:11-alpine
    container_name: psql-naxa
    env_file: pg_env.txt
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-naxa
    env_file: pg_env.txt
    ports:
      - "5051:80"
    restart: always
    depends_on:
      - db

  geoserver:
    image: kartoza/geoserver:2.19.0
    container_name: geoserver-naxa
    env_file: geoserver_env.txt
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8600:8080"
    restart : on-failure
    depends_on:
      - db


volumes:
  postgres-data:
    name: postgres-data
  geoserver-data:
    name: geoserver-data