# Generated by Django 4.1 on 2023-03-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterimage',
            name='extension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rasterimage',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rasterimage',
            name='file',
            field=models.FileField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='rasterimage',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
